version: '3.1'
services:
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        hostname: portainer
        restart: always
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./data:/data
              # - "./cn:/public"
        environment:
            TZ: Asia/Shanghai
            LANG: en_US.UTF-8
        ports:
            - "9443:9443"
            - "8000:8000"
        networks:
            - base
networks:
   base:
        external: true
