version: '3'
console:
        image: styletang/rocketmq-console-ng:latest
        net: "host"
        volumes:
         - /etc/localtime:/etc/localtime:ro
        ports:
         - "18080:8080"
                   #links:
                   #- namesrv:namesrv
        environment:
                JAVA_OPTS: -Drocketmq.config.namesrvAddr=your_ip:9876
