db:
  container_name: pgsql
  restart: always
  image: postgres 
  privileged: true
  ports:
    - 5432:5432 
  environment:
    POSTGRES_PASSWORD: 123456
    PGDATA: /var/lib/postgresql/data/pgdata 
  volumes:
    - ${PWD}/pgdata:/var/lib/postgresql/data/pgdata
