version: "3"
services:
  jupyter:
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /opt/jupyter:/home/jovyan/work
    restart: always
    # image: "jupyter/datascience-notebook"
    image: "jupyter_lab"
