version: "3.0"
services:
  nginx_:
    restart: always
    ports:
      - "88:88"
    volumes:
      - ./data:/usr/share/nginx/html:rw
      - ./conf.d:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx:rw

    image: nginx:latest
    # tty: true
    # network_mode: 
    #   - 
  # web:
  #   image: nginx
  #   volumes:
  #   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  #   ports:
  #   - "80:80"
  #   environment:
  #   - NGINX_HOST=foobar.com
  #   - NGINX_PORT=80
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
