version: "3"
services:
    portainer:
        ports:
        - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
        - portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        image: "portainer/portainer"
volumes:
  portainer_data: