version: '3'
services:
        mysql-server:
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: "passwd"
                image: mysql:latest
                restart: always
                volumes:
                        - "/mnt/mysql/8/db:/var/lib/mysql"
                        - "/mnt/mysql/8/conf:/etc/mysql/conf.d"
                        - "/mnt/data:/var/lib/mysql"

